name: deploy-pages
on:
  push:
    branches: "main"
    paths:
      - Doxyfile
      - README.md
      - src/**
      - include/**
      - docs/**
      - .github/workflows/deploy-pages.yml
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-actions/setup-doxygen@main
      - uses: jcbhmr/configure-pages@jcbhmr-patch-1
      - run: cmake -Bbuild
      - run: cmake --build build -t html
      - uses: actions/upload-pages-artifact@v2
        with:
          path: html
      - id: deploy-pages
        uses: actions/deploy-pages@v2
