name: doxygen
on:
  push:
    branches: "main"
    paths:
      - Doxyfile
      - README.md
      - src/**
      - include/**
      - docs/**
      - .github/workflows/doxygen.yml
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jcbhmr/setup-doxygen@main
      - run: npm ci
      - id: configure-pages
        uses: actions/configure-pages@v3
      - run: echo "BASE_URL=$BASE_URL" >> "$GITHUB_ENV"
        env:
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
      - run: cmake -Bbuild
      - run: cmake --build build --target html
      - uses: actions/upload-pages-artifact@v2
        with:
          path: html
      - id: deploy-pages
        uses: actions/deploy-pages@v2
